UPDATE marcas SET plantilla_tarjeta = NULL WHERE plantilla_tarjeta IN (
  'EDITORIAL_CHECKS', 'TICKET_CHECKS', 'ORBIT_CHECKS', 'SPLIT_CHECKS',
  'EDITORIAL_POINTS', 'TICKET_POINTS', 'ORBIT_POINTS', 'SPLIT_POINTS'
);
ALTER TABLE marcas DROP CONSTRAINT marcas_plantilla_tarjeta_check;
ALTER TABLE marcas ADD CONSTRAINT marcas_plantilla_tarjeta_check CHECK (
  plantilla_tarjeta IS NULL OR plantilla_tarjeta IN (
    'COMIC_HQ', 'MINIMAL_PRO', 'POP_BADGE', 'PREMIUM_GOLD_CHECKS', 'DARK_LUXURY_CHECKS',
    'PREMIUM_GOLD', 'DARK_LUXURY', 'POP_HEADER', 'COMIC_HQ_POINTS', 'MINIMAL_PRO_POINTS',
    'POP_BADGE_POINTS', 'NEON_PULSE', 'SUNSET_GRADIENT'
  )
);
